# Generated by Django 2.1 on 2018-09-13 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_forty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('audio', models.FileField(upload_to='audio_file_forty')),
                ('text', models.TextField()),
                ('segments', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Audio_sixty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('audio', models.FileField(upload_to='audio_file_sixty')),
                ('text', models.TextField()),
                ('segments', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Audio_twenty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('audio', models.FileField(upload_to='audio_file_twenty')),
                ('text', models.TextField()),
                ('segments', models.CharField(max_length=250)),
            ],
        ),
        
    ]
