# Generated by Django 2.1 on 2018-09-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chapter_order', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('length', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='audiofiles')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='audio.Book')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='chapter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Chapter'),
        ),
    ]
