# Generated by Django 2.1 on 2018-09-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_scores_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='correct_answer',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scores',
            name='user_answer',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
