# Generated by Django 2.1 on 2018-09-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20180924_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='missplelled_count',
            new_name='misspelled_count',
        ),
    ]
