# Generated by Django 2.1 on 2018-09-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20180924_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
