# Generated by Django 2.1 on 2018-09-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_auto_20180924_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
