# Generated by Django 2.1 on 2018-09-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_scores_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='book_title',
            field=models.CharField(default='Book title unknown', max_length=250),
            preserve_default=False,
        ),
    ]
