# Generated by Django 2.1 on 2018-09-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_scores_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='book_title',
            field=models.CharField(max_length=255),
        ),
    ]
