# Generated by Django 2.1 on 2018-09-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_auto_20180926_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='chapter_id',
        ),
        migrations.DeleteModel(
            name='Audio_forty',
        ),
        migrations.DeleteModel(
            name='Audio_sixty',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
